[package]
name = "session_send"
version = "0.1.0"
authors = ["usbpc <usbpc@holm.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
ssh2 = { path = ".." }